[package]
name = "justbus-rs"
version = "0.1.0"
authors = ["Budi Syahiddin <budisyahiddin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lta = "0.3.0-async-preview-5"
actix-web = "1.0.5"
lru_time_cache = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.1.29"
parking_lot = "0.9.0"
actix = "0.8.3"

[profile.dev]
opt-level = 3
codegen-units = 1
lto = true

[profile.release]
opt-level = 3
codegen-units = 1
lto = true